name: Add weekday unblocker trigger
description: Request an issue to be created when a condition is met.
title: "Add weekday unblocker trigger: "
body:
  - type: textarea
    id: trigger
    attributes:
      label: Trigger
      description: Describe the condition that should cause the workflow to create an issue.
    validations:
      required: true
  - type: textarea
    id: issue-content
    attributes:
      label: Issue content
      description: Provide the title and body of the issue the workflow should create.
    validations:
      required: true
